/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./components/Auth.vue')['default']
    ChartComponent: typeof import('./components/ChartComponent.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ChatMessage: typeof import('./components/ChatMessage.vue')['default']
    FunctionQueue: typeof import('./components/FunctionQueue.vue')['default']
    Functions: typeof import('./components/Functions.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Landing: typeof import('./components/Landing.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Monaco: typeof import('./components/Monaco.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    Notifier: typeof import('./components/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerEvent: typeof import('./components/ServerEvent.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    Stacks: typeof import('./components/Stacks.vue')['default']
    TextBlock: typeof import('./components/TextBlock.vue')['default']
    TipTap: typeof import('./components/TipTap.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
  }
}
